apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: working-kernel-module-release-ctck4
  namespace: rh-ee-herlich-tenant
  labels:
    appstudio.openshift.io/snapshot: kernel-module-app-ctck4
    appstudio.openshift.io/application: kernel-module-app
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/kernel-module-publish-pipeline.yaml"
  params:
    - name: input-image
      value: "quay.io/herlich/kernel-module@sha256:018eed471de3842d66fbc47144cb65ef1b539544811425e0d45653af9b9c8a9f"
    - name: gitRepoURL
      value: "github.com/HarelErlich/kernel-module-demo-artifacts.git"
    - name: gitRepoTokenSecret
      value: "git-publish-secret"
    - name: s3Endpoint
      value: "https://s3.eu-central-1.wasabisys.com"
    - name: s3Bucket
      value: "my-test-bucket-harel"
    - name: s3CredentialsSecret
      value: "wasabi-publish-secret"
  serviceAccountName: appstudio-pipelines
  workspaces:
    - name: ws-repack
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ws-publish
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
