apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: working-kernel-module-release-c77x9
  namespace: rh-ee-herlich-tenant
  labels:
    appstudio.openshift.io/snapshot: kernel-module-app-c77x9  
    appstudio.openshift.io/application: kernel-module-app
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/kernel-module-publish-pipeline.yaml"
  params:
    - name: input-image
      value: "quay.io/herlich/kernel-module@sha256:17573d6cc4e489548a555be5a83f8c6d1bfdf59bf4a24498be8cfa8efd1f18b7"
    - name: gitRepoURL
      value: "github.com/HarelErlich/kernel-module-demo-artifacts.git"
    - name: gitRepoTokenSecret
      value: "git-publish-secret"
    - name: s3Endpoint
      value: "https://axvbdgx0qi1m.compat.objectstorage.il-jerusalem-1.oraclecloud.com"
    - name: s3Bucket
      value: "bucket-20250917-1359"
    - name: s3CredentialsSecret
      value: "oci-publish-secret"
  serviceAccountName: appstudio-pipelines
  workspaces:
    - name: ws-repack
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ws-publish
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
