apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-to-git
spec:
  description: |
    Downloads the Trusted Artifact, then pushes hello-world.ko to a Git repo.
  params:
    - name: kmod-artifact
      type: string
      description: TA name produced by 'create' (e.g. kmod.tar.gz)
    - name: gitRepoURL
      type: string
      description: "Host/path only, e.g. github.com/ORG/REPO.git"
    - name: gitRepoTokenSecret
      type: string
      description: "Secret with key 'token' for Git auth"
  workspaces:
    - name: source
      description: Workspace
  steps:
    - name: fetch-artifact
      image: busybox:latest
      script: |
        #!/busybox/sh
        set -eux
        DEST="$(workspaces.source.path)/kmod-dist"
        mkdir -p "${DEST}"
        # Extract the tar.gz file
        cd "$(workspaces.source.path)"
        tar -xzf "$(params.kmod-artifact)" -C "${DEST}"
        ls -l "${DEST}"
    - name: push
      # Any image with git and sh will do; keeping yours:
      image: quay.io/konflux-ci/release-service-utils:0f82be4
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.gitRepoTokenSecret)
              key: token
      script: |
        #!/usr/bin/env sh
        set -eux
        git config --global user.email "konflux-ci@redhat.com"
        git config --global user.name "Konflux CI Bot"

        REPO_URL="https://oauth2:${GIT_TOKEN}@$(params.gitRepoURL)"
        CLONE_DIR="$(workspaces.source.path)/repo-clone"
        mkdir -p "${CLONE_DIR}"
        git clone "${REPO_URL}" "${CLONE_DIR}"

        VERSION="$(date +%Y-%m-%d-%H%M%S)"
        mkdir -p "${CLONE_DIR}/${VERSION}"
        cp "$(workspaces.source.path)/kmod-dist/hello-world.ko" "${CLONE_DIR}/${VERSION}/"

        cd "${CLONE_DIR}"
        git add .
        git commit -m "feat: add kernel module ${VERSION}"
        git push origin main
