apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-to-s3
spec:
  description: |
    Downloads the Trusted Artifact, then uploads hello-world.ko to S3.
  params:
    - name: kmod-artifact
      type: string
      description: TA name produced by 'create' (e.g. kmod.tar.gz)
    - name: s3Endpoint
      type: string
    - name: s3Bucket
      type: string
    - name: s3CredentialsSecret
      type: string
      description: Secret with keys aws_access_key_id and aws_secret_access_key
  workspaces:
    - name: source
      description: Workspace
  steps:
    - name: fetch-artifact
      image: busybox:latest
      script: |
        #!/bin/sh
        set -eux
        DEST="$(workspaces.source.path)/kmod-dist"
        mkdir -p "${DEST}"
        # The artifact should be passed as a full path, but let's handle both cases
        ARTIFACT_PATH="$(params.kmod-artifact)"
        if [ ! -f "${ARTIFACT_PATH}" ]; then
          # Try relative to workspace
          ARTIFACT_PATH="$(workspaces.source.path)/$(params.kmod-artifact)"
        fi
        # Extract the tar.gz file
        tar -xzf "${ARTIFACT_PATH}" -C "${DEST}"
        ls -l "${DEST}"
    - name: upload
      image: amazon/aws-cli:2.13.13
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: $(params.s3CredentialsSecret)
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.s3CredentialsSecret)
              key: aws_secret_access_key
        - name: AWS_REGION
          value: "il-jerusalem-1"
        - name: AWS_DEFAULT_REGION
          value: "il-jerusalem-1"
      script: |
        #!/usr/bin/env sh
        set -eux

        echo "================================================="
        echo "INFO: Starting S3 Upload Step"
        echo "================================================="
        
        echo "--- 1. Printing environment variables ---"
        env | sort
        
        
        echo
        echo "--- 3. Verifying AWS config file content ---"
        # The HOME directory in Tekton containers is /tekton/home
        cat /tekton/home/.aws/config || echo "AWS config file not found."
        
        echo
        echo "--- 4. Preparing for upload ---"
        VERSION="$(date +%Y-%m-%d-%H%M%S)"
        SOURCE_FILE="$(workspaces.source.path)/kmod-dist/hello-world.ko"
        DEST_URI="s3://$(params.s3Bucket)/${VERSION}/hello-world.ko"
        
        echo "Source: ${SOURCE_FILE}"
        echo "Destination: ${DEST_URI}"
        echo "Endpoint: $(params.s3Endpoint)"
        
        echo
        echo "--- 5. Attempting to upload file ---"
        aws s3 cp "${SOURCE_FILE}" "${DEST_URI}" \
          --endpoint-url "$(params.s3Endpoint)" \
          --region il-jerusalem-1
        
        echo "================================================="
        echo "INFO: S3 Upload Step Finished"
        echo "================================================="