apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-to-s3
spec:
  description: |
    Downloads the Trusted Artifact, then uploads hello-world.ko to S3.
  params:
    - name: kmod-artifact
      type: string
      description: TA name produced by 'create' (e.g. kmod.tar.gz)
    - name: s3Endpoint
      type: string
    - name: s3Bucket
      type: string
    - name: s3CredentialsSecret
      type: string
      description: Secret with keys aws_access_key_id and aws_secret_access_key
  workspaces:
    - name: source
      description: Workspace
  steps:
    - name: fetch-artifact
      image: busybox:latest
      script: |
        #!/busybox/sh
        set -eux
        DEST="$(workspaces.source.path)/kmod-dist"
        mkdir -p "${DEST}"
        # Extract the tar.gz file
        cd "$(workspaces.source.path)"
        tar -xzf "$(params.kmod-artifact)" -C "${DEST}"
        ls -l "${DEST}"
    - name: upload
      image: amazon/aws-cli:2.13.13
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: $(params.s3CredentialsSecret)
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.s3CredentialsSecret)
              key: aws_secret_access_key
      script: |
        #!/usr/bin/env sh
        set -eux
        VERSION="$(date +%Y-%m-%d-%H%M%S)"
        aws s3 cp \
          "$(workspaces.source.path)/kmod-dist/hello-world.ko" \
          "s3://$(params.s3Bucket)/${VERSION}/hello-world.ko" \
          --endpoint-url "$(params.s3Endpoint)"
