apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: repack-kernel-module
spec:
  description: |
    Extracts hello-world.ko from a container image (no podman),
    then re-packages it as a Trusted Artifact for downstream tasks.
  params:
    - name: input-image
      type: string
      description: Fully-qualified image with digest (e.g. quay.io/...@sha256:...)
  results:
    - name: kmod-artifact
      type: string
      description: Trusted Artifact name to be consumed by "use"
  workspaces:
    - name: source
      description: Workspace for intermediate files
  steps:
    - name: extract-ko
      # crane can export the image filesystem as a tar to stdout
      image: gcr.io/go-containerregistry/crane:debug
      script: |
        #!/busybox/sh
        set -euxo pipefail
        DEST_DIR="$(workspaces.source.path)/extracted"
        mkdir -p "${DEST_DIR}"
        # Export the image and extract the module file
        crane export "$(params.input-image)" - \
          | tar -x -C "${DEST_DIR}" hello-world.ko
        ls -l "${DEST_DIR}"

    - name: create-ta
      # Create a simple tar.gz file instead of using Trusted Artifacts
      image: busybox:latest
      script: |
        #!/busybox/sh
        set -eux
        SRC="$(workspaces.source.path)/extracted/hello-world.ko"
        # Create a simple tar.gz file
        cd "$(workspaces.source.path)"
        tar -czf kmod.tar.gz -C extracted hello-world.ko
        # Expose the artifact name to downstream tasks
        echo -n "kmod.tar.gz" > "$(results.kmod-artifact.path)"
