apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: repack-kernel-module
spec:
  description: |
    Extracts hello-world.ko from a container image (no podman),
    then re-packages it as a Trusted Artifact for downstream tasks.
  params:
    - name: input-image
      type: string
      description: Fully-qualified image with digest (e.g. quay.io/...@sha256:...)
  results:
    - name: kmod-artifact
      type: string
      description: Trusted Artifact name to be consumed by "use"
  workspaces:
    - name: source
      description: Workspace for intermediate files
  steps:
    - name: extract-ko
      # crane can export the image filesystem as a tar to stdout
      image: gcr.io/go-containerregistry/crane:debug
      script: |
        #!/busybox/sh
        set -euxo pipefail
        DEST_DIR="$(workspaces.source.path)/extracted"
        mkdir -p "${DEST_DIR}"
        # Export the image and extract the module file
        crane export "$(params.input-image)" - \
          | tar -x -C "${DEST_DIR}" hello-world.ko
        ls -l "${DEST_DIR}"

    - name: create-ta
      # This image provides the 'create' CLI for Trusted Artifacts
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest
      script: |
        #!/usr/bin/env sh
        set -eux
        SRC="$(workspaces.source.path)/extracted/hello-world.ko"
        # Create a TA named 'kmod.tar.gz' from the single file
        create --from "${SRC}" kmod.tar.gz
        # Expose the TA name to downstream tasks
        echo -n "kmod.tar.gz" > "$(results.kmod-artifact.path)"
