# konflux-config/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-release-pipeline-role
  namespace: rh-ee-herlich-tenant
rules:
  # Allow the pipeline to read secrets for Git and S3 credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-release-pipeline-rolebinding
  namespace: rh-ee-herlich-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-release-pipeline-role
subjects:
  # This binds the role to the default pipeline service account
  - kind: ServiceAccount
    name: pipeline