# konflux-config/release-plan.yaml
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: kernel-module-release-plan
  namespace: rh-ee-herlich-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "true"
spec:
  application: kernel-module-app
  tenantPipeline:
    pipelineRef:
      # This tells the Release Service to fetch the pipeline from Git
      resolver: git
      params:
        - name: url
          value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
        - name: revision
          value: "main" # Or the branch you are working on
        - name: pathInRepo
          value: "pipelines/release-pipeline.yaml" # The path to our pipeline file
    params:
      # These are the parameters for the pipeline itself
      - name: storeInGit
        value: "true"
      - name: storeInS3
        value: "true"