# konflux-config/release-plan.yaml
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: kernel-module-release-plan
  namespace: rh-ee-herlich-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "true"
spec:
  application: kernel-module-app
  tenantPipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/HarelErlich/konflux-kernel-module-demo.git
        - name: revision
          value: main
        - name: pathInRepo
          value: konflux-config/pipelines/tenant-release-pipeline.yaml
    # THIS IS THE FIX: Explicitly run the pipeline with our new ServiceAccount
    serviceAccountName: tenant-release-sa
    params:
      - name: gitRepoURL
        value: "github.com/HarelErlich/kernel-module-demo-artifacts.git"
      - name: gitRepoTokenSecret
        value: "git-publish-secret"
      - name: s3Endpoint
        value: "https://s3.eu-north-1.amazonaws.com"
      - name: s3Bucket
        value: "herlich-kmods-storage-20250907"
      - name: s3CredentialsSecret
        value: "s3-publish-secret"