# pipelines/debug-pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: debug-pipeline
spec:
  description: A minimal pipeline that just prints a message.
  tasks:
    - name: say-hello
      taskSpec:
        steps:
          - name: echo
            image: busybox:latest
            script: |
              #!/bin/sh
              set -eux
              echo "Hello from the auto-release! If you see this, the trigger is working."