apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kernel-module-publish-pipeline
  namespace: rh-ee-herlich-tenant
spec:
  description: >
    Repackage the built kernel module from a container image and publish it to Git, S3-compatible storage, and Azure Blob Storage.
    Tasks are resolved from Git via the Tekton "git" resolver.

  params:
    - name: input-image
      type: string
      description: "Image pullspec with digest, e.g. quay.io/herlich/kernel-module@sha256:..."
    - name: gitRepoURL
      type: string
      description: "Target Git repo host/path (no scheme), e.g. github.com/HarelErlich/kernel-module-demo-artifacts.git"
      default: "github.com/HarelErlich/kernel-module-demo-artifacts.git"
    - name: gitRepoTokenSecret
      type: string
      default: git-publish-secret
      description: "K8s Secret name with key 'token' for Git push auth"
    - name: s3Endpoint
      type: string
      description: "S3 endpoint, e.g. https://s3.us-east-1.amazonaws.com"
    - name: s3Bucket
      type: string
      description: "Destination S3 bucket"
    - name: s3CredentialsSecret
      type: string
      description: "K8s Secret name with aws_access_key_id / aws_secret_access_key"
    - name: azureStorageAccount
      type: string
      description: "Azure Storage account name"
    - name: azureContainer
      type: string
      description: "Azure Blob container name"
    - name: azureSpSecret
      type: string
      description: "K8s Secret with AZURE_TENANT_ID / AZURE_CLIENT_ID / AZURE_CLIENT_SECRET"
      default: azure-blob-sp-secret

  workspaces:
    - name: ws-repack
    - name: ws-publish

  tasks:
    - name: repack-kernel-module
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/repack-kernel-module.yaml"
      params:
        - name: input-image
          value: "$(params.input-image)"
      workspaces:
        - name: source
          workspace: ws-repack

    - name: push-to-git
      runAfter: [repack-kernel-module]
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/push-to-git.yaml"
      params:
        - name: kmod-artifact
          value: "$(tasks.repack-kernel-module.results.kmod-artifact)"
        - name: gitRepoURL
          value: "$(params.gitRepoURL)"
        - name: gitRepoTokenSecret
          value: "$(params.gitRepoTokenSecret)"
      workspaces:
        - name: source
          workspace: ws-repack

    - name: push-to-s3
      runAfter: [repack-kernel-module]
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/push-to-s3.yaml"
      params:
        - name: kmod-artifact
          value: "$(tasks.repack-kernel-module.results.kmod-artifact)"
        - name: s3Endpoint
          value: "$(params.s3Endpoint)"
        - name: s3Bucket
          value: "$(params.s3Bucket)"
        - name: s3CredentialsSecret
          value: "$(params.s3CredentialsSecret)"
      workspaces:
        - name: source
          workspace: ws-repack

    - name: push-to-azure
      runAfter: [repack-kernel-module]
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/HarelErlich/konflux-kernel-module-demo.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/push-to-azure.yaml"
      params:
        - name: kmod-artifact
          value: "$(tasks.repack-kernel-module.results.kmod-artifact)"
        - name: azureStorageAccount
          value: "$(params.azureStorageAccount)"
        - name: azureContainer
          value: "$(params.azureContainer)"
        - name: azureSpSecret
          value: "$(params.azureSpSecret)"
      workspaces:
        - name: source
          workspace: ws-repack
