# konflux-config/pipelines/tenant-release-pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kernel-module-tenant-release
spec:
  description: >-
    This pipeline releases the kernel module artifact by repackaging it
    from the build container and publishing it to external storage.
  
  params:
    - name: snapshot
      type: string
    - name: gitRepoURL
      type: string
    - name: gitRepoTokenSecret
      type: string
    - name: s3Endpoint
      type: string
    - name: s3Bucket
      type: string
    - name: s3CredentialsSecret
      type: string

  tasks:
    - name: get-image-url
      taskSpec:
        params:
          - name: snapshot
            type: string
        results:
          - name: image-url
            type: string
        steps:
          - name: get-image-from-snapshot
            # This image contains oc, kubectl, jq, etc.
            image: quay.io/konflux-ci/release-service-utils:0f82be4 
            script: |
              #!/usr/bin/env sh
              set -ex

              # The snapshot param is a namespaced name, e.g., "my-ns/my-snapshot"
              # We use it with 'oc get' to fetch the full JSON object.
              SNAPSHOT_JSON=$(oc get snapshot "$(params.snapshot)" -o json)
              
              # Now that we have the real JSON, we can use jq safely.
              IMAGE_URL=$(echo "$SNAPSHOT_JSON" | jq -r '.spec.components[] | select(.name == "kernel-module") | .containerImage')
              
              echo -n "$IMAGE_URL" | tee $(results.image-url.path)
      params:
        - name: snapshot
          value: $(params.snapshot)

    - name: repack-kernel-module
      runAfter: ["get-image-url"]
      params:
        - name: input-image
          value: $(tasks.get-image-url.results.image-url)
      taskSpec:
        params:
          - name: input-image
            type: string
        results:
          - name: kmod-artifact
            type: string
        volumes:
          - name: scratch-space
            emptyDir: {}
        steps:
          - name: extract-ko-file
            # Use a general-purpose image with skopeo to extract the file
            image: quay.io/konflux-ci/release-service-utils:0f82be4 
            volumeMounts:
              - name: scratch-space
                mountPath: /scratch
            script: |
              #!/usr/bin/env sh
              set -ex
              # Skopeo copies the entire image filesystem to a directory
              skopeo copy "docker://$(params.input-image)" "dir:/scratch/image-contents"
              
              # Find the .ko file inside the extracted filesystem and copy it
              find /scratch/image-contents -name 'hello-world.ko' -exec cp {} /scratch/hello-world.ko \;

          - name: create-artifact
            # Now use the specialized image just for creating the artifact
            image: quay.io/redhat-appstudio/build-trusted-artifacts:latest
            volumeMounts:
              - name: scratch-space
                mountPath: /scratch
            script: |
              #!/usr/bin/env sh
              set -ex
              cd /scratch
              # Create the new artifact from the extracted .ko file
              create --from hello-world.ko kmod.tar.gz
              echo -n kmod.tar.gz | tee $(results.kmod-artifact.path)

    # Note: push-to-git and push-to-s3 tasks remain the same as the last version
    - name: push-to-git
      runAfter: ["repack-kernel-module"]
      params:
        - name: kmod-artifact
          value: $(tasks.repack-kernel-module.results.kmod-artifact)
        - name: gitRepoURL
          value: $(params.gitRepoURL)
        - name: gitRepoTokenSecret
          value: $(params.gitRepoTokenSecret)
      taskSpec:
        params:
          - name: kmod-artifact
            type: string
          - name: gitRepoURL
            type: string
          - name: gitRepoTokenSecret
            type: string
        volumes:
          - name: scratch-space
            emptyDir: {}
        steps:
          - name: fetch-and-push
            image: quay.io/konflux-ci/release-service-utils:0f82be4
            volumeMounts:
              - name: scratch-space
                mountPath: /scratch
            script: |
              #!/usr/bin/env sh
              set -ex
              cd /scratch
              use "$(params.kmod-artifact)=./kmod-dist"
              git config --global user.email "konflux-ci@redhat.com"
              git config --global user.name "Konflux CI Bot"
              GIT_URL_WITH_AUTH="https://oauth2:$(GIT_TOKEN)@$(params.gitRepoURL)"
              git clone "$GIT_URL_WITH_AUTH" ./repo-clone
              VERSION=$(date +%Y-%m-%d-%H%M%S)
              mkdir -p ./repo-clone/$VERSION
              cp ./kmod-dist/hello-world.ko ./repo-clone/$VERSION/
              cd ./repo-clone
              git add .
              git commit -m "feat: Add kernel module version $VERSION"
              git push origin main
            env:
              - name: GIT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: $(params.gitRepoTokenSecret)
                    key: token

    - name: push-to-s3
      runAfter: ["repack-kernel-module"]
      params:
        - name: kmod-artifact
          value: $(tasks.repack-kernel-module.results.kmod-artifact)
        - name: s3Endpoint
          value: $(params.s3Endpoint)
        - name: s3Bucket
          value: $(params.s3Bucket)
        - name: s3CredentialsSecret
          value: $(params.s3CredentialsSecret)
      taskSpec:
        params:
          - name: kmod-artifact
            type: string
          - name: s3Endpoint
            type: string
          - name: s3Bucket
            type: string
          - name: s3CredentialsSecret
            type: string
        volumes:
          - name: scratch-space
            emptyDir: {}
        steps:
          - name: fetch-and-upload
            image: amazon/aws-cli:2.13.13
            volumeMounts:
              - name: scratch-space
                mountPath: /scratch
            script: |
              #!/usr/bin/env sh
              set -ex
              cd /scratch
              use "$(params.kmod-artifact)=./kmod-dist"
              VERSION=$(date +%Y-%m-%d-%H%M%S)
              aws s3 cp ./kmod-dist/hello-world.ko s3://$(params.s3Bucket)/$VERSION/hello-world.ko --endpoint-url $(params.s3Endpoint)
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: $(params.s3CredentialsSecret)
                    key: aws_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: $(params.s3CredentialsSecret)
                    key: aws_secret_access_key